version: '3'

networks:
  laravel:

services:
  site-nginx:
    image: nginx:stable-alpine
    container_name: nginx-container-php7
    ports:
      - 8090:80
    volumes:
      - ./src:/var/www/html:delegated
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php7-service
    networks:
      - laravel

  php7-service:
    build:
      context: ./src
      dockerfile: php.dockerfile
    container_name: php7-container
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel
  
  # react frontend
  frontend-service:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: frontend-container
    command: yarn start
    depends_on:
      - site-nginx
    ports:
      - "3003:3000"
    volumes:
      - ./front-end:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - laravel

